<?php

namespace Database\Seeders;

use App\Models\Ticket;
use App\Models\TicketResponse;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class HelpdeskTicketSeeder extends Seeder
{
    public function run(): void
    {
        $dummyTickets = [
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0001',
                'user_id'            => 4,
                'nama_pelapor'       => 'Budi Santoso',
                'email_pelapor'      => 'budi.santoso@company.com',
                'departemen_pelapor' => 'Marketing',
                'lokasi_pelapor'     => 'Gd. A Lt. 2 Meja 12',
                'barang_id'          => 524,
                'assigned_to'        => 14,
                'kategori'           => 'Hardware / Perangkat',
                'prioritas'          => 'Tinggi',
                'status'             => 'In Progress',
                'judul'              => 'Keyboard laptop tombol Spasi dan Enter sering macet',
                'deskripsi'          => 'Tombol Spasi dan Enter pada laptop kerja sering tidak merespon saat mengetik laporan bulanan. Mohon bantuan pengecekan atau penggantian keyboard.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subDays(2)->setHour(9)->setMinute(15),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 4,
                        'nama_pengirim'     => 'Budi Santoso',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Tinggi].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDays(2)->setHour(9)->setMinute(15),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'response',
                        'pesan'             => 'Halo Pak Budi, tiket sudah kami terima dan ditugaskan. Tim IT Support akan ke meja Anda untuk melakukan inspeksi hardware keyboard.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'In Progress',
                        'created_at'        => Carbon::now()->subDays(2)->setHour(10)->setMinute(30),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0002',
                'user_id'            => 5,
                'nama_pelapor'       => 'Siti Nurhaliza',
                'email_pelapor'      => 'siti.nurhaliza@company.com',
                'departemen_pelapor' => 'Finance',
                'lokasi_pelapor'     => 'Gd. B Lt. 1 Ruang Kasir',
                'barang_id'          => null,
                'assigned_to'        => 14,
                'kategori'           => 'Software & Aplikasi',
                'prioritas'          => 'Kritis',
                'status'             => 'Resolved',
                'judul'              => 'Aplikasi ERP / Accounting error 500 saat generate laporan faktur pajak',
                'deskripsi'          => 'Muncul pop-up Internal Server Error (500) saat mencoba mengekspor rekap transaksi faktur pajak akhir bulan.',
                'solusi'             => 'Dilakukan clearing cache session pada server database ERP dan pembaruan module connector ODBC. Masalah berhasil teratasi dan export faktur berjalan normal.',
                'created_at'         => Carbon::now()->subDays(3)->setHour(11)->setMinute(0),
                'resolved_at'        => Carbon::now()->subDays(2)->setHour(14)->setMinute(30),
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 5,
                        'nama_pengirim'     => 'Siti Nurhaliza',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Kritis].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDays(3)->setHour(11)->setMinute(0),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'response',
                        'pesan'             => 'Sedang kami koordinasikan dengan database administrator untuk restart service connector dan clearing query lock pada modul faktur.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'In Progress',
                        'created_at'        => Carbon::now()->subDays(3)->setHour(11)->setMinute(45),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Status tiket diubah menjadi [Resolved]. Solusi telah diterapkan dan terverifikasi berhasil.',
                        'status_sebelumnya' => 'In Progress',
                        'status_setelahnya' => 'Resolved',
                        'created_at'        => Carbon::now()->subDays(2)->setHour(14)->setMinute(30),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0003',
                'user_id'            => 6,
                'nama_pelapor'       => 'Ahmad Fauzi',
                'email_pelapor'      => 'ahmad.fauzi@company.com',
                'departemen_pelapor' => 'Human Capital',
                'lokasi_pelapor'     => 'Gd. A Lt. 3 Meja 05',
                'barang_id'          => null,
                'assigned_to'        => 1,
                'kategori'           => 'Email & Akun / Akses',
                'prioritas'          => 'Sedang',
                'status'             => 'Closed',
                'judul'              => 'Reset password akun email korporat & konfigurasi ulang 2FA',
                'deskripsi'          => 'Akun email Outlook kantor terkunci karena salah memasukkan password. Mohon bantuan reset password dan panduan setting OTP Authenticator.',
                'solusi'             => 'Password email sementara telah digenerate dan dikirimkan secara aman. 2FA Authenticator telah berhasil diaktifkan kembali oleh user.',
                'created_at'         => Carbon::now()->subDays(5)->setHour(8)->setMinute(40),
                'resolved_at'        => Carbon::now()->subDays(5)->setHour(10)->setMinute(15),
                'closed_at'          => Carbon::now()->subDays(4)->setHour(16)->setMinute(0),
                'responses'          => [
                    [
                        'user_id'           => 6,
                        'nama_pengirim'     => 'Ahmad Fauzi',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Sedang].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDays(5)->setHour(8)->setMinute(40),
                    ],
                    [
                        'user_id'           => 1,
                        'nama_pengirim'     => 'SUPERADMIN',
                        'tipe'              => 'response',
                        'pesan'             => 'Kredensial sementara telah dikirimkan via SMS terdaftar. Silakan login dan ubah kata sandi baru.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'Closed',
                        'created_at'        => Carbon::now()->subDays(4)->setHour(16)->setMinute(0),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0004',
                'user_id'            => 7,
                'nama_pelapor'       => 'Dewi Lestari',
                'email_pelapor'      => 'dewi.lestari@company.com',
                'departemen_pelapor' => 'Operasional',
                'lokasi_pelapor'     => 'Gd. C Lt. 1 Gudang Barat',
                'barang_id'          => 532,
                'assigned_to'        => null,
                'kategori'           => 'Jaringan & Internet',
                'prioritas'          => 'Tinggi',
                'status'             => 'Open',
                'judul'              => 'PC workstation logistik terputus dari jaringan LAN lokal',
                'deskripsi'          => 'Lampu indikator port LAN di belakang PC tidak menyala. Sudah coba cabut-pasang kabel RJ45 namun koneksi tetap Network Cable Unplugged.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subHours(4),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 7,
                        'nama_pengirim'     => 'Dewi Lestari',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Tinggi].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subHours(4),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0005',
                'user_id'            => 8,
                'nama_pelapor'       => 'Rian Hidayat',
                'email_pelapor'      => 'rian.hidayat@company.com',
                'departemen_pelapor' => 'Purchasing',
                'lokasi_pelapor'     => 'Gd. A Lt. 2 Meja 20',
                'barang_id'          => null,
                'assigned_to'        => 14,
                'kategori'           => 'Printer & Scanner',
                'prioritas'          => 'Sedang',
                'status'             => 'In Progress',
                'judul'              => 'Printer network sharing sering offline dan paper jam',
                'deskripsi'          => 'Printer departemen purchasing di lantai 2 sering berstatus offline di Windows dan kertas sering macet pada tray penarik.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subDay()->setHour(13)->setMinute(20),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 8,
                        'nama_pengirim'     => 'Rian Hidayat',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Sedang].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDay()->setHour(13)->setMinute(20),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'note',
                        'pesan'             => 'Roller penarik kertas sedang dibersihkan dan IP printer di-lock statis pada DHCP server.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'In Progress',
                        'created_at'        => Carbon::now()->subDay()->setHour(15)->setMinute(0),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0006',
                'user_id'            => 9,
                'nama_pelapor'       => 'Maya Putri',
                'email_pelapor'      => 'maya.putri@company.com',
                'departemen_pelapor' => 'Sekretariat',
                'lokasi_pelapor'     => 'Gd. Utama Lt. 2 Ruang Direksi',
                'barang_id'          => 525,
                'assigned_to'        => 14,
                'kategori'           => 'Hardware / Perangkat',
                'prioritas'          => 'Kritis',
                'status'             => 'In Progress',
                'judul'              => 'Layar laptop bergaris vertikal hitam dan baterai drop drastis',
                'deskripsi'          => 'Terdapat garis vertikal tebal di layar laptop Lenovo ThinkPad, serta baterai hanya bertahan 10 menit setelah charger dicabut. Butuh penanganan segera untuk rapat pimpinan besok.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subHours(6),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 9,
                        'nama_pengirim'     => 'Maya Putri',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Kritis].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subHours(6),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'note',
                        'pesan'             => 'Perangkat dipindahkan ke Lab IT dan disiapkan unit pengganti sementara (laptop backup).',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'In Progress',
                        'created_at'        => Carbon::now()->subHours(5),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0007',
                'user_id'            => 10,
                'nama_pelapor'       => 'Eko Prasetyo',
                'email_pelapor'      => 'eko.prasetyo@company.com',
                'departemen_pelapor' => 'Legal & Compliance',
                'lokasi_pelapor'     => 'Gd. B Lt. 3 Meja 08',
                'barang_id'          => null,
                'assigned_to'        => 1,
                'kategori'           => 'Software & Aplikasi',
                'prioritas'          => 'Rendah',
                'status'             => 'Resolved',
                'judul'              => 'Request instalasi Adobe Acrobat Pro & konfigurasi sertifikat digital',
                'deskripsi'          => 'Membutuhkan lisensi dan instalasi Adobe Acrobat Pro pada laptop untuk keperluan review kontrak dan pembubuhan e-meterai resmi perusahaan.',
                'solusi'             => 'Lisensi volume enterprise Adobe Acrobat DC telah diaktifkan dan sertifikat digital tanda tangan telah dikonfigurasi.',
                'created_at'         => Carbon::now()->subDays(4)->setHour(10)->setMinute(10),
                'resolved_at'        => Carbon::now()->subDays(3)->setHour(16)->setMinute(45),
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 10,
                        'nama_pengirim'     => 'Eko Prasetyo',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Rendah].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDays(4)->setHour(10)->setMinute(10),
                    ],
                    [
                        'user_id'           => 1,
                        'nama_pengirim'     => 'SUPERADMIN',
                        'tipe'              => 'response',
                        'pesan'             => 'Instalasi paket aplikasi dan sertifikat telah selesai dikonfigurasi melalui remote session.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'Resolved',
                        'created_at'        => Carbon::now()->subDays(3)->setHour(16)->setMinute(45),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0008',
                'user_id'            => 11,
                'nama_pelapor'       => 'Nina Wijaya',
                'email_pelapor'      => 'nina.wijaya@company.com',
                'departemen_pelapor' => 'Customer Care',
                'lokasi_pelapor'     => 'Gd. A Lt. 1 Call Center',
                'barang_id'          => 533,
                'assigned_to'        => 14,
                'kategori'           => 'Jaringan & Internet',
                'prioritas'          => 'Tinggi',
                'status'             => 'Pending',
                'judul'              => 'Telepon VoIP Call Center sering putus audio (jitter)',
                'deskripsi'          => 'Saat melayani telepon pelanggan, suara penelepon sering terputus-putus dan terdengar delay tinggi pada meja agent 04.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subDay()->setHour(14)->setMinute(0),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 11,
                        'nama_pengirim'     => 'Nina Wijaya',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Tinggi].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDay()->setHour(14)->setMinute(0),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'response',
                        'pesan'             => 'Sedang dilakukan QoS bandwidth monitoring pada switch VLAN voice. Menunggu konfirmasi kestabilan dari ISP backbone.',
                        'status_sebelumnya' => 'Open',
                        'status_setelahnya' => 'Pending',
                        'created_at'        => Carbon::now()->subDay()->setHour(16)->setMinute(30),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0009',
                'user_id'            => 12,
                'nama_pelapor'       => 'Rizky Ramadhan',
                'email_pelapor'      => 'rizky.ramadhan@company.com',
                'departemen_pelapor' => 'Quality Assurance',
                'lokasi_pelapor'     => 'Gd. C Lt. 2 Lab Uji',
                'barang_id'          => null,
                'assigned_to'        => null,
                'kategori'           => 'Permintaan Pengadaan / Fasilitas',
                'prioritas'          => 'Sedang',
                'status'             => 'Open',
                'judul'              => 'Permintaan kabel HDMI 5 Meter & converter Type-C to HDMI',
                'deskripsi'          => 'Diperlukan kabel HDMI panjang 5 meter dan adaptor multi-port Type-C to HDMI untuk display ruang presentasi QA & audit ISO.',
                'solusi'             => null,
                'created_at'         => Carbon::now()->subHours(2),
                'resolved_at'        => null,
                'closed_at'          => null,
                'responses'          => [
                    [
                        'user_id'           => 12,
                        'nama_pengirim'     => 'Rizky Ramadhan',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Sedang].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subHours(2),
                    ],
                ],
            ],
            [
                'no_tiket'           => 'ITH-' . date('dmY') . '-0010',
                'user_id'            => 13,
                'nama_pelapor'       => 'Anita Rahmawati',
                'email_pelapor'      => 'anita.rahmawati@company.com',
                'departemen_pelapor' => 'R&D / Tech',
                'lokasi_pelapor'     => 'Gd. B Lt. 2 Tech Hub',
                'barang_id'          => 526,
                'assigned_to'        => 14,
                'kategori'           => 'Hardware / Perangkat',
                'prioritas'          => 'Sedang',
                'status'             => 'Closed',
                'judul'              => 'Permohonan upgrade RAM 8GB ke 16GB untuk kompilasi kode',
                'deskripsi'          => 'Laptop kerja saat ini menggunakan RAM 8GB dan sering freeze saat menjalankan container Docker dan IDE secara bersamaan.',
                'solusi'             => 'Telah dipasangkan keping RAM DDR4 8GB tambahan (Total menjadi 16GB Dual Channel). Pengujian memori lulus uji stabilitas.',
                'created_at'         => Carbon::now()->subDays(6)->setHour(10)->setMinute(0),
                'resolved_at'        => Carbon::now()->subDays(5)->setHour(15)->setMinute(30),
                'closed_at'          => Carbon::now()->subDays(5)->setHour(17)->setMinute(0),
                'responses'          => [
                    [
                        'user_id'           => 13,
                        'nama_pengirim'     => 'Anita Rahmawati',
                        'tipe'              => 'status_change',
                        'pesan'             => 'Tiket bantuan IT resmi dibuat dengan status [Open] dan prioritas [Sedang].',
                        'status_sebelumnya' => null,
                        'status_setelahnya' => 'Open',
                        'created_at'        => Carbon::now()->subDays(6)->setHour(10)->setMinute(0),
                    ],
                    [
                        'user_id'           => 14,
                        'nama_pengirim'     => 'Muhammad Permana (Admin)',
                        'tipe'              => 'response',
                        'pesan'             => 'Keping RAM 8GB DDR4 telah terpasang dan lolos uji benchmark memori. Unit siap digunakan kembali.',
                        'status_sebelumnya' => 'In Progress',
                        'status_setelahnya' => 'Closed',
                        'created_at'        => Carbon::now()->subDays(5)->setHour(17)->setMinute(0),
                    ],
                ],
            ],
        ];

        foreach ($dummyTickets as $item) {
            $responses = $item['responses'] ?? [];
            unset($item['responses']);

            $ticket = Ticket::updateOrCreate(
                ['no_tiket' => $item['no_tiket']],
                $item
            );

            // Bersihkan respon lama jika ada untuk idempotency
            $ticket->responses()->delete();

            foreach ($responses as $resp) {
                $resp['ticket_id'] = $ticket->id;
                TicketResponse::create($resp);
            }
        }
    }
}
